[supervisord]
 nodaemon        = true
 logfile         = /dev/null
 logfile_maxbytes= 0

 [program:assp]
 process_name    = assp
 autostart       = true
 autorestart     = true
 directory       = /usr/share/assp
 command         = /usr/share/assp/assp.pl
 startsecs       = 0
